# Generated by Django 4.2.5 on 2023-09-24 16:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_salesfunnelcategory_salesfunnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='salesfunnel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='salesfunnel',
            name='peoples',
        ),
        migrations.AddField(
            model_name='salesfunnel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesfunnel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesfunnel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salesfunnel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='SalesFunnelCategory',
        ),
        migrations.AddField(
            model_name='funnelstage',
            name='sales_funnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.salesfunnel'),
        ),
    ]
