# Generated by Django 4.2.5 on 2023-09-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_funnelstage_remove_salesfunnel_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesfunnel',
            options={'ordering': ['-created']},
        ),
    ]
