# Generated by Django 4.2.5 on 2023-11-27 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_project', models.CharField(choices=[('practical_work', 'Практическая работа'), ('independent work', 'Cамостоятельная работа'), ('Project', 'Проект')], max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content_html', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='project_photos/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
