# Generated by Django 4.2.5 on 2023-11-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_attendance_course_projectstudent_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='is_present',
            new_name='status',
        ),
    ]
