# Generated by Django 4.2.5 on 2023-12-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_is_present_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstudent',
            name='stars',
            field=models.IntegerField(blank=True, choices=[(1, '1 звезд'), (2, '2 звезд'), (3, '3 звезд'), (4, '4 звезд'), (5, '5 звезд')]),
        ),
        migrations.AlterField(
            model_name='projectstudent',
            name='type_of_project',
            field=models.CharField(choices=[('practical_work', 'Практическая работа'), ('independent_work', 'Cамостоятельная работа'), ('project', 'Проект')], max_length=100),
        ),
    ]
