# Generated by Django 4.2.5 on 2023-10-23 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingstudent',
            name='points',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='Баллы должны быть не меньше 1.'), django.core.validators.MaxValueValidator(25, message='Баллы должны быть не больше 25.')]),
        ),
    ]
