# Generated by Django 4.2.5 on 2023-12-13 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_student_solution_user'),
        ('account', '0006_alter_projectstudent_stars'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileStudent',
            new_name='ProgressStudent',
        ),
    ]
