# Generated by Django 4.2.5 on 2023-10-24 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_duration'),
        ('account', '0007_alter_ratingstudent_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingstudent',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
