# Generated by Django 4.2.5 on 2024-01-08 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_solution_grade'),
        ('account', '0008_delete_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressstudent',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
    ]
