# Generated by Django 4.2.5 on 2023-10-29 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_award_profilestudent_delete_ratingstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestudent',
            name='points',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Баллы должны быть не меньше 0.'), django.core.validators.MaxValueValidator(25, message='Баллы должны быть не больше 25.')]),
        ),
    ]
