version: '3'

services:
  server:
    build: .
    container_name: drf
    restart: always
    command:
      - bash
      - -c
      - "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usta_server
    ports:
      - "8000:8000"