import Calendar from "../../Mentor/Schedule/components/Calendar";

const StudentSchedule = () => {
    const lessonsData = [
        {
          id: 1,
          title: 'Введение в веб разработку',
          date: '2023-11-01',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 1',
        },
        {
          id: 2,
          title: 'Занятие 2',
          date: '2023-11-03',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 2',
        },
        {
          id: 3,
          title: 'Занятие 3',
          date: '2023-11-06',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 2',
        },
        {
          id: 4,
          title: 'Занятие 4',
          date: '2023-11-08',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 2',
        },
        {
          id: 5,
          title: 'Занятие 5',
          date: '2023-11-10',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 2',
        },
        {
          id: 6,
          title: 'Занятие 5',
          date: '2023-11-13',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 2',
        },
        {
          id: 7,
          title: 'Занятие 5',
          date: '2023-11-15',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 2',
        },
        {
          id: 8,
          title: 'Занятие 5',
          date: '2023-11-17',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 2',
        },
        {
          id: 9,
          title: 'Занятие 5',
          date: '2023-11-20',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 2',
        },
        {
          id: 10,
          title: 'Занятие 5',
          date: '2023-11-22',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 2',
        },
        {
          id: 11,
          title: 'Занятие 5',
          date: '2023-11-24',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 2',
        },
        {
          id: 1,
          title: 'Введение в веб разработку',
          date: '2023-12-01',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 1',
        },
        {
          id: 2,
          title: 'Занятие 2',
          date: '2023-12-04',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 2',
        },
        {
          id: 3,
          title: 'Занятие 3',
          date: '2023-12-06',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 2',
        },
        {
          id: 4,
          title: 'Занятие 4',
          date: '2023-12-08',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 2',
        },
        {
          id: 5,
          title: 'Занятие 5',
          date: '2023-12-11',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 2',
        },
        {
          id: 6,
          title: 'Занятие 5',
          date: '2023-12-13',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 2',
        },
        {
          id: 7,
          title: 'Занятие 5',
          date: '2023-12-15',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 2',
        },
        {
          id: 8,
          title: 'Занятие 5',
          date: '2023-12-18',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 2',
        },
        {
          id: 9,
          title: 'Занятие 5',
          date: '2023-12-20',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 2',
        },
        {
          id: 10,
          title: 'Занятие 5',
          date: '2023-12-22',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 2',
        },
        {
          id: 11,
          title: 'Занятие 5',
          date: '2023-12-25',
          startTime: '15:30',
          endTime: '17:00',
          description: 'Описание занятия 2',
        },
      ];
  return (
    <div>
    <Calendar year={2023} month={10} lessons={lessonsData} />
      <Calendar year={2023} month={11 } lessons={lessonsData} />
    </div>
  )
}

export default StudentSchedule