# Generated by Django 4.2.5 on 2023-11-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
