# Generated by Django 4.2.5 on 2023-11-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='content_html/images/')),
            ],
        ),
        migrations.RenameField(
            model_name='content',
            old_name='description',
            new_name='content_html',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='content_html',
        ),
    ]
