# Generated by Django 4.2.5 on 2023-11-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_end_time_alter_course_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='days_of_week',
            field=models.CharField(max_length=14),
        ),
    ]
