# Generated by Django 4.2.5 on 2023-11-12 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_alter_course_days_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='submission_date',
        ),
        migrations.AlterField(
            model_name='solution',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
