# Generated by Django 4.2.5 on 2023-10-24 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='Баллы должны быть не меньше 1.'), django.core.validators.MaxValueValidator(100, message='Баллы должны быть не больше 100.')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ManyToManyField(related_name='exam_course', to='course.course')),
            ],
        ),
    ]
