# Generated by Django 4.2.5 on 2024-01-08 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_score_solution_grade_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Баллы должны быть не меньше 1.')]),
        ),
    ]
